apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-registration-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-registration
  template:
    metadata:
      labels:
        app: event-registration
    spec:
      containers:
        - image: jstrem/registration-image:2021-12-31-02-20-05
          name: event-registration
          env:
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
              value: jdbc:postgresql://fanny.db.elephantsql.com:5432/bukqntkr
            - name: KUMULUZEE_DATASOURCES0_USERNAME
              value: bukqntkr
            - name: KUMULUZEE_DATASOURCES0_PASSWORD
              value: E2SE5Ru_O6OGntAqsOJqi-7QClTANW6d
            - name: KUMULUZEE_DISCOVERY_CLUSTER
              value: minikube
            - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
              value: http://etcd:2379
              #valueFrom:
              #  secretKeyRef:
              #    name: pg-pass
              #    key: KUMULUZEE_DATASOURCES0_PASSWORD
          ports:
            - containerPort: 8080
              name: server
              protocol: TCP
          #livenessProbe:
#            httpGet:
#              path: /health/live
#              port: server
#            initialDelaySeconds: 20 # kolk nj na za훾etk po훾aka (훾e bi blo premal bi kubernetes skos na novo zagajnou ke nebi delal)
#            periodSeconds: 3 # perioda s katero kubernetes kli훾e to
#          readinessProbe:
#            httpGet:
#              path: /health/ready
#              port: server
#            initialDelaySeconds: 20
#            periodSeconds: 3

---

apiVersion: v1
kind: Service
metadata:
  name: event-registration
spec:
  type: LoadBalancer
  ports:
    - port: 3333
      protocol: TCP
      targetPort: server
  selector:
    app: event-registration
