kumuluzee:
  name: event-registration-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  config:
    start-retry-delay-ms: 20
    max-retry-delay-ms: 900000
    etcd:
      hosts: http://localhost:2379
  discovery:
    cluster: 1
    etcd:
      hosts: http://localhost:2379
    ttl: 20
    ping-interval: 15
  datasources:
    - jndi-name: jdbc/Climb
#       connection-url: jdbc:postgresql://climb-db:5432/climb-db
#      connection-url: jdbc:postgresql://localhost:5432/climb-db
#      username: dbuser
#      password: postgres
      connection-url: jdbc:postgresql://fanny.db.elephantsql.com:5432/bukqntkr
      username: bukqntkr
      password: E2SE5Ru_O6OGntAqsOJqi-7QClTANW6d
      max-pool-size: 1
rest-properties:
  maintenance-mode: false
#  print: Config print
