kumuluzee:
  name: event-registration-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/Climb
      # connection-url: jdbc:postgresql://climb-db:5432/climb-db
      #connection-url: jdbc:postgresql://localhost:5432/climb-db
      # username: dbuser
      # password: postgres
      connection-url: jdbc:postgresql://fanny.db.elephantsql.com:5432/bukqntkr
      username: bukqntkr
      password: E2SE5Ru_O6OGntAqsOJqi-7QClTANW6d
      max-pool-size: 1
  cors-filter:
    servlet:
      allow-generic-http-requests: true
      allow-origin: "*"
    annotations:
      my-resource:
        allow-origin: "http://localhost:4200"
        allow-subdomains: true
        supported-methods: "GET, POST, DELETE, HEAD, OPTIONS, PUT"
  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                             <Configuration name="comments">
                                 <Appenders>
                                     <Console name="console" target="SYSTEM_OUT">
                                         <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                                     </Console>
                                     <Socket name="logstash" host="c19fcec3-312f-478b-b14f-bdaeb6520873-ls.logit.io"
                                     port="26369" protocol="udp">
                                         <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                                     </Socket>
                                 </Appenders>
                                 <Loggers>
                                     <!-- Default logger -->
                                     <Root level="all">
                                         <AppenderRef ref="console" level="info" />
                                         <AppenderRef ref="logstash" level="info" />
                                     </Root>
                                 </Loggers>
                             </Configuration>'
  rest-client:
    registrations:
      - class: notification-api
        url: http://20.120.67.65/notifications/v1
        read-timeout: 5000
  config:
    consul:
      agent: http://20.120.67.65/consul
rest-properties:
  maintenance-mode: false

